name: bachelor2026
channels:
  - conda-forge

dependencies:
  - python=3.11.4

  # Datahåndtering
  - pandas
  - numpy

  # Statistikk / regresjon
  - linearmodels

  # Visualisering
  - matplotlib
  - altair

  # Database
  - duckdb

  # Jupyter / kernel
  - jupyter
  - ipykernel

  # pip-pakker
  - pip
  - pip:
      # Dashboard
      - streamlit

      # API / data
      - requests
      - geopy

      # Azure / miljø
      - azure-storage-blob
      - python-dotenv

      # Tid / helligdager
      - holidays